server:
  port: 8080

spring:
  application:
    name: wechat-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    com.ms.wx: debug

management:
  endpoints:
    web:
      base-path: /health
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
        step: PT15S